config/routes.rb
Rails.application.routes.draw do
  resources :soundcloud_queries

  root 'soundcloud_queries#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/soundcloud_user.rb
class SoundcloudUser < ApplicationRecord
  serialize :user_hash

  def data
    OpenStruct.new(self.user_hash)
  end

  def data=(hash)
    hash.each do |k,v|
      self.user_hash[k] = v
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/soundcloud_queries_controller.rb
class SoundcloudQueriesController < ApplicationController
  def new

  end

  def index
    @users = SoundcloudUser.all
  end

  def create
    sc_user_data = Query.new.get_user(parse_params[:username]).symbolize_keys
    @soundcloud_user = SoundcloudUser.new(
      { user_name: sc_user_data[:username],
        user_hash: JSON.parse(sc_user_data.to_json).symbolize_keys})
    if @soundcloud_user.save
      redirect_to soundcloud_query_path(@soundcloud_user.id)
    else
      redirect_to root_path
    end
  end

  def show
    @soundcloud_user = SoundcloudUser.find params[:id]
  end

  private

    def soundcloud_query_params
      params.require(:soundcloud_url).permit(:username)
    end

    def parse_params
      if params[:soundcloud_url].include?('http')
        params[:username] = params[:soundcloud_url].split('/').last
      else
        params[:username] = params[:soundcloud_url]
      end
      params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/soundcloud_query_helper.rb
module SoundcloudQueryHelper
end

app/helpers/soundcloud_user_helper.rb
module SoundcloudUserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleSoundcloudApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/soundcloud_queries/_form.html.erb
<%= form_tag soundcloud_queries_path do %>
  <%= label_tag(:soundcloud_url, "Please enter a valid Soundcloud Artist URL or USERNAME:") %>
  <%= text_field_tag(:soundcloud_url) %>
  <%= submit_tag("Let's go!") %>
<% end %>

app/views/soundcloud_queries/create.html.erb
<h1> <%= @soundcloud_url %> </h1>
<%= @user %>
<%= link_to 'Save to database', '/soundcloud_queries/show' %>

app/views/soundcloud_queries/index.html.erb
<h1>SoundcloudQuery#index</h1>
<%= link_to 'New Query', '/soundcloud_queries/new' %>
<hr>
<% @users.each do |u| %>
	<%= link_to u.user_hash[:permalink_url], target: '_blank' do %>
		<div><%= u.id %></div>
		<div>	Soundcloud username: <%= u.user_name  %></div>
		<div>	Soundcloud url: <%= u.user_hash[:permalink_url]%></div>
		<br>
	<% end %>
<% end %>

app/views/soundcloud_queries/new.html.erb
<h1>SoundcloudQuery#new</h1>
<p>Find me in app/views/soundcloud_query/new.html.erb</p>
<%= render 'form' %>

app/views/soundcloud_queries/show.html.erb
<h1>SoundcloudQuery#show</h1>
<%= @soundcloud_user.user_name %>
<%= @soundcloud_user.user_hash.inspect %>
<br>
<div>
	<hr>
	<%= link_to 'home', root_path %>
</div>

app/views/soundcloud_query/_form.html.erb
<%= form_tag '/show' do %>
  <%= label_tag(:soundcloud_url, "Please enter a valid Soundcloud Artist URL:") %>
  <%= text_field_tag(:soundcloud_url) %>
  <%= submit_tag("Let's go!") %>
<% end %>